### ISSUE TITLE
Lev Landau 朗道

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadAct#358]
Somehow my computer refuses searches in pdfs... can you add for the PS00605 entry (Classical Theory of Fields) whether it was neibu? (Fang Lizhi writes that it was banned).

**Comment by LenaHenningsen** [comment]
(and if there is a neibu edition, please add that into the publication fields, too)

**Comment by HUANG0421** [comment]
According to the introduction from Baidu, this book is very popular after its publication. 

> 《烈火金钢》出版后，“……不论大街小巷，或是穷乡僻壤，凡是有收音机或大喇叭的地方，平头百姓都尖着耳朵听‘肖飞买药’。就这样，在五六十年代《烈火金钢》就印了上百万册。”中国青年出版社的黄伊是《烈火金钢》1958年出版时的责任编辑，生前他在《我所知道的〈烈火金钢〉》中这样评说该书出版后在群众中产生的热烈反响。

And it has far-reaching implications for many readers and has even been adapted into a TV series due to its "anti-Japanese" theme.
So i don't have enough evidence to show that it was a neibu publication. :)
