### ISSUE TITLE
Fictional Reading Acts

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#366]
@LenaHenningsen @duncdrum @damianodamiani @HUANG0421 @EveYLin 

Some questions came up during our last teleconference regarding the integration of fictional reading acts to the data.

Can we put fictional and non-fictional acts together or rather how to separate them?

Can non-fictional acts be recorded in fictional texts?

And what should we do with the categorization of SecondarySources in 01 informational works, 02 literary non-fiction, 03 fiction, as we have it in Act.csv ?

**Comment by LenaHenningsen** [comment]
I am answering below, as relates my experiment on Monday.

 

Von: Mira Grünwald <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 14. März 2019 um 06:39
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Mention <mention@noreply.github.com>
Betreff: [readchina/ReadingData] Fictional Reading Acts (#366)

 

@LenaHenningsen @duncdrum @damianodamiani @HUANG0421

Some questions came up during our last teleconference regarding the integration of fictional reading acts to the data.

Can we put fictional and non-fictional acts together or rather how to separate them?

                I am not entirely sure what’s best, but I would opt for separation, as I find it important for the analysis to keep them separate; 1) we need to analyse fictional / non-fictional entities on their own; then, maybe we can go for 2) comparison

Can non-fictional acts be recorded in fictional texts?

                Puh, I suppose yes; that would be, say, that Goethe writes a historical novel about Shakespeare and describes him reading Plato; BUT: then we need to be certain that Shakespeare really read this particular text by Plato. I have one shouchaoben in which Zhou Enlai reads some work by Mao Zedong. Yes, ZEL surely read MZD; and surely also that text. But in the fictional text, the factual nature does not matter. The reading act is not an ethnographic recording. Rather, it has a factual claim to describe better this fictional ZEL. 

And what should we do with the categorization of SecondarySources in 01 informational works, 02 literary non-fiction, 03 fiction, as we have it in Act.csv ?

                I added a 3 for the reading acts; not sure that works to separate things well…

Conversely, I came up with the following issues

In a fictional text we have a number of times. Or maybe time levels:
Time of publication (when the piece of fiction was first published), this is recorded of course
Time of narration
Time of reading. 
For example: In a 1980 published book Open Love Letters, Zhenzhen in 1970 mentions a reading act that still matters to her, but that took place during her childhood
So, for the reading act, maybe the connection to the character’s bio is more relevant (and precise) than a date: was something a childhood reading? Youth / mid-age / old-age reading?
To me this suggests that we need different categories, and maybe a different file for reading acts in fictional texts.

Two more things:
We may now have texts that previously came up as primary source in the secondary sources! 
I would also like to record intertextual references in the fictional texts more broadly; i.e. when literary references appear within a different text or so… but need to think about that.
If you want, I could join for the telco next week? (will need to try the software first, though).

Thanks a lot,

Lena

**Comment by duncdrum** [comment]
Some quick thoughts:

This is a question of revising the data model as such we need to take very literal views of words such as `all`, `always`, etc. Lena's point seems good, ie `non-fictional` reading acts in `fictional` sources can occur. Therefore,  we cannot determine the fictionality of the act by looking at the source's genre category.

1.  We can however determine the fictionality of personas and sources on their own, e.g. `Harry Potter` (fictional persona), `Book of Spells` (fictional book). This leads to simple matrix:

    |Person|Object|act|
    |---|---|---|
    |F|F|F|
    |¬F|F|x|
    |F|¬F|F|
    |¬F|¬F|¬F|

    1.  Purely fictional act, exist when both agent and source are fictional, e.g. `Hermione` reads the `Book of Spells`.
    2.  non-fictional persons can claim to have read fictional sources, but thats never a truthfull reading act, e.g. ~~`Trump` reads the `Book of Spells`~~
    3.  Fictional Personas can read non-fictional texts, e.g.`Jean Luc Picard` reads `Hamlet`, in my view thats a fictional act.  
    4.  If both agent and object are non-fictional the resulting act, is non-fictional.
    
In other words we can determine the fictionality of an act by the fictionality of the persona, which raises the following points:

-   By marking the act as fictional we can separate fictional ZJM readings from non-fictional without duplicating our Person records by introducing `ZJM(f)` in addition to `ZJM(¬f)`
-   The genre classification of a source as `03` doesn't really tell us if a source or an act is fictional.
    -   There is a difference between claiming a source is fictional, `Book of Spells` and claiming that `Harry Potter and the Deathly Hallows` is in the `fiction` genre. There is a great overlap with respect to the reading acts involving these two to be fictional, but they are different distinctions. 
-   All tricky cases fall into the `iv` category: Ie a source with genre `03` in which both person and object are non-fictional. We can record a distinction by declaring the `act` to be `F` or `¬F`, so the model support this. But why and when should we choose one over the other, and how can we ensure to do so consistently?

**Comment by LenaHenningsen** [comment]
THanks a lot.

I think I need an actual discussion of these issues to fully understand.

What is ZJM?

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 14. März 2019 um 12:23
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Mention <mention@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Fictional Reading Acts (#366)

 

Some quick thoughts:

This is a question of revising the data model as such we need to take very literal views of words such as all, always, etc. Lena's point seems good, ie non-fictional reading acts in fictional sources can occur. Therefore, we cannot determine the fictionality of the act by looking at the source's genre category.
We can however determine the fictionality of personas and sources on their own, e.g. Harry Potter (fictional persona), Book of Spells (fictional book). This leads to simple matrix:
PersonObjectact
FFF
¬FFx
F¬FF
¬F¬F¬F
Purely fictional act, exist when both agent and source are fictional, e.g. Hermione reads the Book of Spells.
non-fictional persons can claim to have read fictional sources, but thats never a truthfull reading act, e.g. Trump reads the Book of Spells
Fictional Personas can read non-fictional texts, e.g.Jean Luc Picard reads Hamlet, in my view thats a fictional act.
If both agent and object are non-fictional the resulting act, is non-fictional.
In other words we can determine the fictionality of an act by the fictionality of the persona, which raises the following points:
By marking the act as fictional we can separate fictional ZJM readings from non-fictional without duplicating our Person records by introducing ZJM(f) in addition to ZJM(¬f)
The genre classification of a source as 03 doesn't really tell us if a source or an act is fictional. 
There is a difference between claiming a source is fictional, Book of Spells and claiming that Harry Potter and the Deathly Hallows is in the fiction genre. There is a great overlap with respect to the reading acts involving these two to be fictional, but they are different distinctions.
All tricky cases fall into the iv category: Ie a source with genre 03 in which both person and object are non-fictional. We can record a distinction by declaring the act to be F or ¬F, so the model support this. But why and when should we choose one over the other, and how can we ensure to do so consistently?

**Comment by duncdrum** [comment]
no idea, i meant `ZEL`

**Comment by LenaHenningsen** [comment]
Ok, thanks

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 14. März 2019 um 14:11
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Mention <mention@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Fictional Reading Acts (#366)

 

no idea, i meant ZEL

**Comment by LenaHenningsen** [comment]
Thank you I am fine with this.

**Comment by duncdrum** [comment]
## Fictional persons:
### Data to be recorded in `acts table`
#### Social status 
(not to be confused with social status!) refers to
what the narrative reveals about the fictional person \>\> maybe
`political status`?

For texts from the realm of Socialist Realism, these ascriptions are
typically very clear (the social status can vary across the narrative,
i.e. someone might turn from positive to negative etc.)

-   Member of the CCP
-   Martyr (i.e. died for the cause of the CCP)
-   Participant in the underground struggle (pre-49)
-   Middle character 中间人物
-   Ordinary person
-   We also need the possibility of having no info here, because for
    some categories we cannot know this
-   Class enemy

>   Maybe too many categories?

#### Narrative age
 (I think this is better than the social age we discussed): narrative age records the relative age of the protagonist
 at the time of action. The category is, by its nature, not tied to a
 very explicit age, but rather slightly vague:

-   Childhood
-   Youth: middle school through college students; young workers
-   Mid-age (roughly corresponds to getting married and having young
    kids)
-   Old age

#### Act type
-   Make an intertextual reference

### Data to be recorded in the `person table`
 **Narrative status** records the narrative function of the character.
 Also, here we can leave things open for very minor characters, I
 guess. Would be important to record the status of the main characters.
 (Again, can we maybe allow to add two labels??)

-   Narrator
-   Protagonist
-   Main hero

 **Narrator** should be added as a person into the person table as
 **narratorial voice**. Potential reading act: Narratorial voice can
 make an intertextual reference to a text XYZ.

**Comment by duncdrum** [comment]
@LenaHenningsen 

`political_status` should either be new entries in `SocialPosition` or in its own table (I prefer the former) if we want to differentiate between `party members` as a real life attribute and as a literary trope we could define the social position entry eg: `party member (trope)` but i think one attribute `party member` should suffice for both historical and fictional agents

I would also encourage us to stick with keeping `political status` as a primary attribute of persons, `martyr` `resistance fighter` etc do not change and are attributes or persons not acts.

Similarly `narrative age` can change in the course of a book, but doesn't have to. Often a hero will be `mid-age` throughout a book, so instead of having to provide this for every reading act we can simply incorporate that in the description in `Person.csv` once.  The possible values should be defined in the data-dictionary ( i would replace `mid-age` with `adulthood`)

In cases where reading acts happen during a change in `political_status` or `narrative_age` of a protagonist we should indeed record them in `Act.csv` so that the attributes provided there **override** the default attribute recorded in `Person.csv`

I m not sure what the difference is between `Protagonist` and `Main Hero`, but if we want to include more then two attributes we should create a new table `NarrativePositon.csv` and collect possible values there. The keys should appear in `Person.csv` if we have no instances of a fictional person e.g. being the hero in one text, and the villain in another. Otherwise we should add the `narrative_status` keys to `Act.csv` using a similar override mechanism as with `political_status`

I m not sure what you mean by `Act type` but fictional reading should certainly be an act_type, others TBD.

The number of categories seems fine to me, the question is do we want to differentiate between `empty` and `unknown` or not. This would allow us to record intentionally vague information, as different from us not knowing.
