### ISSUE TITLE
Narrative status in The Class Teacher

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#414]
Hello @LenaHenningsen and @duncdrum 
We have either 'NarrativePosition' or 'SocialPosition' to give the narrative status of the fictional persons.

Martyr
Middle character
Ordinary person
Class enemy
Participant in the underground struggle

or

higher cadre
lower cadre
intellectual
executive
high-ranking military officer
middle class
worker
peasant
common soldier

I just started to add some info on protagonists in _The Class Teacher_ by Liu Xinwu and was wondering how to deal with their narrative status, which are described as "activist"or "protagonist".
I'm not sure to which table I should add them.

**Comment by LenaHenningsen** [comment]
I think that social position and narrative position should not be conflated: Because someone could be a martyr and a worker. 

Then we should also have protagonist / main character as a category there, right? And supporting character as well. The five categories listed below all pint to the socialist realism framework, they are not meaningful for anything that is written post Mao…

 

Von: Mira Grünwald <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Donnerstag, 24. Oktober 2019 um 19:32
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Mention <mention@noreply.github.com>
Betreff: [readchina/ReadingData] Narrative status in The Class Teacher (#414)

 

Hello @LenaHenningsen and @duncdrum
We have either 'NarrativePosition' or 'SocialPosition' to give the narrative status of the fictional persons.

Martyr
Middle character
Ordinary person
Class enemy
Participant in the underground struggle

or

higher cadre
lower cadre
intellectual
executive
high-ranking military officer
middle class
worker
peasant
common soldier

I just started to add some info on protagonists in The Class Teacher by Liu Xinwu and was wondering how to deal with their narrative status, which are described as "activist"or "protagonist".
I'm not sure to which table I should add them.

**Comment by mira-gruenwald** [comment]
Ok. Then I think it would be helpful to give an explanation in the data-dictionary that the first five categories are only relevant for works of socialist realism, right? And should we give a reference/ source to those categories as we do in Genre.csv (Library of Congress)?
