### ISSUE TITLE
Dumas: Count of Monte Cristo

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadAct#456]
I just had a look on the database results on the homepage: what happened to the Count of Monte Cristo? I can't find him there, but didn't he have 10 hits or so?? Thanks much!

**Comment by duncdrum** [comment]
![Screenshot 2021-03-22 at 12 23 07](https://user-images.githubusercontent.com/6205362/111982564-6a573a00-8b09-11eb-8d7a-a7cd53c68b41.png)

@whalekeykeeper can you follow up on this `W0084` is the work in question

**Comment by whalekeykeeper** [comment]
Sure. Will have a look today.

**Comment by duncdrum** [comment]
@whalekeykeeper did you follow up on this?

**Comment by duncdrum** [comment]
ok to get to the bottom of the case of the missing count; 

the sql query responsible for constructing the view data is [here](https://github.com/readchina/ReadAct/blob/11cb98d4a31b36a2ab50c8b09894ea2077ccec59/.github/workflows/ci.yml#L91). 

```sql
select distinct a.act_id, a.act_object, ps.title from Act a, PrimarySource ps inner join PrimarySource on a.act_object = ps.prim_source_id  where ps.title_lang = a.id_lang and a.act_object!='W0414'
```

while two lines below the view in the screenshot above contains the correct data
```sql
select distinct a.act_id, a.act_object, w.creator, (select distinct ps.title from PrimarySource ps where a.act_object = ps.prim_source_id) as title, (select distinct coalesce(p.family_name, '') || ' ' || coalesce(p.first_name, '') from Person p where w.creator = p.person_id) as name from Act a, Work w inner join Work on a.act_object = w.work_id where a.act_object!='W0414'
```

we need to adjust these queries to return the correct results. Alternatively replace the sql query with an xquery run via basex (that outputs csv) and queries the xml files instead of the csv.

**Comment by whalekeykeeper** [comment]
checked the returned value for both SQL queries.
Returned by the first query:

![Screen Shot 2021-08-15 at 11 30 58 PM](https://user-images.githubusercontent.com/46596921/129493434-8710a4b3-4049-4c39-a869-2cef7a4160a5.png)

Returned by the second query:

![Screen Shot 2021-08-15 at 11 29 08 PM](https://user-images.githubusercontent.com/46596921/129493398-0243d53e-967b-4fcc-a923-dca63b6ee589.png)

**Comment by whalekeykeeper** [comment]
I think the problem is:
`title_lang` for `Le Comte de Monte-Cristo` is `fr`, while the SQL query has where clause `where ps.title_lang = a.id_lang`.
All the values in the `id_lang` field in `Act.csv` are `en`.
Therefore, the SQL query will not return a book name in French.

![Screen Shot 2021-08-15 at 11 38 11 PM](https://user-images.githubusercontent.com/46596921/129493602-739d1804-b4cd-4701-a09f-74904dae3e18.png)

**Comment by duncdrum** [comment]
well done, thank you

![Screenshot 2021-08-18 at 13 43 14](https://user-images.githubusercontent.com/6205362/129892355-4d2619cc-1a67-412e-81a6-74362278df1b.png)
