### ISSUE TITLE
data pattern modification to suit ReadActor

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#497]
Hi @duncdrum 
The fields `modified_by` and `last_modified_by` are restricted to have 2 letters.
To make the schema to be compatible with `ReadActor`, should we update this?
Or should we use initials `RA` to represent `ReadActor` for now?

**Comment by duncdrum** [comment]
Actual I would change the pattern to be `2 letters` (for humans) or `ReadActor`

**Comment by whalekeykeeper** [comment]
@duncdrum  Another similar question, year has a pattern `\\[?(-?[0-9X]{4}[\\.~\\?%,]?\\.?){1,2}\\]?` in `person.json` and `"minLength": 4` in `institution.json`
Why it is allowed to have characters like `%` and `.`? Like `1956%.`

Will you prefer to keep these patterns? 
If yes, I will go to update the years in Person.csv and Institution.csv. And update the code in Wikidatalookup accordingly. 
Like `-345` -> `-0345`, `1938.0` -> `1938`

**Comment by duncdrum** [comment]
@whalekeykeeper these date formats are all covered by the ISO scheme referenced in the data dictionary. So yes readactor needs to output valid dates `-345` is not a valid year,  top of my head `1938.0` is also invalid because of `0` but i m not 100%. 

You should assume that the pattern is correct, and make sure that the date from readactor adhere to them. From the looks of it, there was some auto-correction that deleted leading `0`, or turned the cell contents into doubles. From the csv perspective these cells should be treated as `string` and no auto-formatting should be applied.

**Comment by duncdrum** [comment]
PS.: can you link the commit that introduces `ReadActor` into the scheme from the commit message please, thx.

**Comment by duncdrum** [comment]
closed by #498
